### ISSUE TITLE
bug: lazy.nvim reports error with docs

### ISSUE THREAD

**Issue by guiltiest-gear** [VidocqH/auto-indent.nvim#2]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

EndeavourOS

### Describe the bug

When first installing or updating auto-indent.nvim, lazy.nvim throws an error, with the error code of E154, indicating a duplicate tag, which appears to be occurring in the file of my-template-docs.txt.

### Steps To Reproduce

1. Install this plugin with lazy.nvim
2. lazy.nvim will show a docs failed indication next to auto-indent.nvim

### Expected Behavior

There should be no error when updating or installing.

**Comment by VidocqH** [comment]
Oh sorry, I forgot about the template file. Deleted now. Should be fixed

**Comment by guiltiest-gear** [comment]
Yep, pulled to latest commit, error has been fixed

**Comment by VidocqH** [comment]
> Yep, pulled to latest commit, error has been fixed

Seems like the conflict error you saw indicates an author from your plugin list also forgets to delete the template file. 😂😂
