### ISSUE TITLE
Video plugins

### ISSUE THREAD

**Issue by HaleTom** [VidocqH/auto-indent.nvim#3]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Please tell what plugins you use for the slide cursor and indent highlighting.

It looks great!

### Describe the solution you'd like

Maybe even add to readme.md?

### Describe alternatives you've considered

Asking Reddit?

**Comment by VidocqH** [comment]
Smooth Cursor is powered by [neovide/neovide](https://github.com/neovide/neovide), which is a neovim GUI software, I don't think it is possible to make such effect in terminal😂. Other GUI apps like [goneovim](https://github.com/akiyosi/goneovim) can do the same thing.

For indent part, I use two indent highlighting plugins at the same time.

1. [indent-blankline.nvim](https://github.com/lukas-reineke/indent-blankline.nvim)
    To draw the dimmed indent indicator of every indent. For example:
    <img width="59" alt="image" src="https://github.com/VidocqH/auto-indent.nvim/assets/16725418/d60e61b0-c11f-4f99-bcd6-cb84839e3397">

2. [echasnovski/mini.indentscope](https://github.com/echasnovski/mini.indentscope)
    To draw the animated indent of current scoped which is the golden line in the video.

**Comment by HaleTom** [comment]
Thanks heaps!!
