### ISSUE TITLE
bug: Not working in JSX

### ISSUE THREAD

**Issue by scc02** [VidocqH/auto-indent.nvim#4]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2037+ge09adfdcf

### Operating system/version

Ventura 13.3.1 

### Describe the bug

![QQ20240110-155846-HD](https://github.com/VidocqH/auto-indent.nvim/assets/22486446/f9599881-0310-4147-b8e8-3b3920b46db7)

### Steps To Reproduce

1.   {
    'vidocqh/auto-indent.nvim',
    opts = {},
    event = "InsertEnter"
  }
2. edit in jsx Element

### Expected Behavior

Working in jsx Element

**Comment by VidocqH** [comment]
https://github.com/VidocqH/auto-indent.nvim/assets/16725418/1ce9c9de-f81f-45a3-abd1-23b3aefaf65a

Works normal on my side, maybe conflicts with other plugins, seems like associates with #1, helps needed.

**Comment by tan-wei** [comment]
See here: #5 
Probably you should disable lazy load.

**Comment by scc02** [comment]
@tan-wei
```
  {
    'vidocqh/auto-indent.nvim',
    opts = {},
    -- event = "InsertEnter"
  }
```
After removing Lazyload event,It works as expected, Thank you
